version: "3"

services:
  chronograf:
    image: chronograf:latest
    ports:
      - '8888:8888'
    volumes:
      - chronograf_data:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
      - VIRTUAL_HOST=chronograf.plambert.dev
      - VIRTUAL_PORT=8888
      - LETSENCRYPT_HOST=chronograf.plambert.dev
      - TOKEN_SECRET=${TOKEN_SECRET}
      - GH_CLIENT_ID=${GH_CLIENT_ID}
      - GH_CLIENT_SECRET=${GH_CLIENT_SECRET}
      - GH_ORGS=${GH_ORGS}
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb
    environment:  
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - VIRTUAL_HOST=grafana.plambert.dev
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=grafana.plambert.dev
  home-logger:
    image: plambert26/home-logger-server
    restart: always
    ports:
      - 3001:3001 
    environment:
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
      - VIRTUAL_HOST=logger.plambert.dev
      - VIRTUAL_PORT=3001
      - LETSENCRYPT_HOST=logger.plambert.dev

networks:
  default:
    external:
      name: nginx-proxy

volumes:
  influxdb_data:
  chronograf_data:
  grafana_data:
